### PR TITLE
Properly shutdown an ExecutorService that is created locally.

### PR DESCRIPTION
**Pull request by acardona**
When the ExecutorService is created locally (because a null is provided), then the service was never shutdownNow(), and the threads lingered around, consuming native memory.

This fix ensures that, when created locally, the service is properly shut down.

Notice that, when the service is created locally, invoking convolve() more than once will result in an error, because it will attempt to use a terminated service.

This fix is related to an error that emerged in the Trainable Segmentation plugin, where the use of Gabor filters resulted in exhaustion of native memory due to accumulation of unterminated threads.

### CODE REVIEW

**Comment by tpietzsch** [comment]
Fine with me.

In the interest of consistency, consider changing the mechanics to something similar to
https://github.com/imglib/imglib2-algorithm/blob/a1165a6b49ee86fdf0efdde08799d0060d2d5fa7/src/main/java/net/imglib2/algorithm/convolution/AbstractMultiThreadedConvolution.java#L24-L57
instead of using `is_service_local`.

**Comment by acardona** [comment]
The issue is that ```FFTConvolution#setExecutorService(ExecutorService)``` specified in the documentation that if the argument is null, a new one would be created. If I implement it in the way that you suggest, then I would still have to track whether the service was created or not. Or, instead, add an additional method to be able to retrieve the service, and then add the burden to the caller to actually shut it down.

**Comment by tpietzsch** [comment]
I made the change and pushed a commit to show what I meant. Are you fine with it?

**Comment by acardona** [comment]
As long as the error is fixed, works for me.

**Comment by acardona** [comment]
Should this be merged?

**Comment by tpietzsch** [comment]
IT is merged already

**Pull request merged**
